# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hiennguyen92.github.io
date_format: "ordinal"
title: Hien Nguyen
subtitle: "Try try again"
description: "Hien Nguyen's personal blog"
keywords: Hien Nguyen, hiennguyen92, hiennv
timezone: Asia/Ho_chi_minh
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Hien Nguyen
organization: hiennguyen92.github.io
organization_url: http://hiennguyen92.github.io
github_username: hiennguyen92
location: Ho Chi Minh, Viet Nam
email: hiennguyen92@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: hiennguyen92/hiennguyen92.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: hiennguyen92
    repo: blog-comments
    oauth:
        client_id: 620844dd41c076d96aa7
        client_secret: d7992e44b1cdee2001b89e4bb55d0bccf9f2b2af
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: hiennguyen92
    repo: blog-comments
    clientID: 620844dd41c076d96aa7
    clientSecret: d7992e44b1cdee2001b89e4bb55d0bccf9f2b2af
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-87733915-1
